[workspace]
members = ["gb-core","macros", "my-lib"]

[package]
name = "testouille-emulator-future"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
futures-util = "0.3.31"
minifb = "0.28.0"
gb-core = { path = "./gb-core" }
env_logger = "0.11.8"

[dev-dependencies]
arrayvec = "0.7.6"

[profile.release]
overflow-checks = true
debug = true

[profile.test]
opt-level = 3
