name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      - name: Clippy
        run: cargo clippy --workspace --all-targets
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install RGBDS
        run: |
          curl -L -o rgbds-linux-x86_64.tar.xz https://github.com/gbdev/rgbds/releases/latest/download/rgbds-linux-x86_64.tar.xz
          mkdir rgbds
          tar xf rgbds-linux-x86_64.tar.xz -C rgbds
          cd rgbds
          sudo ./install.sh
      - name: Restore cached downloads
        id: cache
        uses: actions/cache@v4
        with:
          path: downloads
          key: download-cache-${{ hashFiles('download-test-roms.sh') }}
          restore-keys: |
            download-cache-
      - name: Download test roms
        if: steps.cache.outputs.cache-hit != 'true'
        run: bash download-test-roms.sh
      - name: Compile home-made roms
        working-directory: gebeh-test-roms
        run: bash build.sh
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: cargo nextest r -p gebeh-core -p gebeh --no-fail-fast
