name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install ALSA development packages
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      - name: Clippy
        run: cargo clippy --workspace --all-targets
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Restore cached downloads
        id: cache
        uses: actions/cache@v4
        with:
          path: downloads
          key: download-cache-${{ hashFiles('download-test-roms.sh') }}
          restore-keys: |
            download-cache-
      - name: Download test roms
        if: steps.cache.outputs.cache-hit != 'true'
        run: bash download-test-roms.sh
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: cargo nextest r -p gebeh-core -p gebeh --no-fail-fast
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [clippy, tests]

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
